---
# Using ansible-playbook 4-12-greet.yml -e greeting="New value"

- name: Pass a message on the command line
  hosts: localhost
  vars:
    greeting: "you didn't specify a message"
  tasks:
    - name: Output a message
      debug:
        msg: "{{ greeting }}"
