# generic/ubuntu2310
# debian/buster64
Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
  end

  (1..2).each do |i|
    config.vm.define "vm0#{i}" do |vm|
      vm.vm.box = "debian/buster64"
      vm.vm.provider :libvirt do |libvirt|
        libvirt.memory = 512
        libvirt.cpus = 1
      end
      vm.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml" # Prepare the playbook for install some packages: htop, mc... 
      end
    end
  end

  config.vm.define "vm03" do |vm03|
    vm03.vm.box = "debian/buster64"
      vm03.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 1
    end
  end
  config.vm.define "vm03" do |vm03|
    vm03.vm.box = "debian/buster64"
      vm03.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 1
    end
  end
  config.vm.define "prometheus" do |prometheus|
    prometheus.vm.box = "debian/buster64"
      prometheus.vm.provider "libvirt" do |libvirt|
      prometheus.vm.hostname = "prometheus"
      libvirt.memory = 2048
      libvirt.cpus = 1
    end
    prometheus.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml" # Prepare the playbook for install some packages: htop, mc... 
    end
  end
end
